services:
  - type: web
    name: bot-ventas-libres-peru
    env: node
    plan: free
    buildCommand: npm install --omit=dev --no-audit --no-fund
    startCommand: node src/index.js
    envVars:
      - key: NODE_VERSION
        value: 22.14.0
      - key: PORT
        value: 10000
      - key: BOT_TOKEN
        sync: false
      - key: OWNER_IDS
        sync: false
      - key: SUPABASE_URL
        sync: false
      - key: SUPABASE_SERVICE_KEY
        sync: false
      - key: PUBLIC_BURN_CHANNEL_ID
        sync: false
      - key: STAFF_CHAT_ID
        sync: false
      - key: ESCROW_GROUP_ID
        sync: false
      - key: LOG_CHANNEL_ID
        sync: false
      - key: BURN_CHAT_ID
        sync: false
